### ISSUE TITLE
Docker compose image not found for netshot

### ISSUE THREAD

**Issue by ChadPunk** [netfishers-onl/Netshot#208]
After cloning the repo to device I have tried:

`docker-compose up -d`

This fails with the following error:

`ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.`

The option prompts for us to continue or cancel. If you continue the new error becomes:

`ERROR: pull access denied for netshot, repository does not exist or may require 'docker login': denied: requested access to the resource is denied`

Sudo permissions should not be needed but the same result when using the elevated version of the commands. 
I tried doing the suggested docker login with no resolve.

**Comment by ChadPunk** [comment]
Changing the docker-compose.yml file
from:
```
services:
  netshot:
    image: netshot
    restart: always
```

to

```
services:
  netshot:
    image: wkleinhenz/netshot
    restart: always

```

Resolves the issue and builds correctly.
